[package]
name = "pdf_merger"
version = "0.1.0"
authors = ["Jan Müller <jan.m.muller@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.26.0"
